import { CompositionItems, FaqItem, FollowupMessage, RoiItem } from "../types";

interface SalesKitResultProps {
  composition: CompositionItems;
  telegramPostText: string;
  roiData: RoiItem[];
  faqData: FaqItem[];
  followupMessages: FollowupMessage[];
  copiedId: string | null;
  onDownloadPDF: () => void;
  onCopyToClipboard: (text: string, id: string) => void;
}

export function SalesKitResult({ composition, telegramPostText, roiData, faqData, followupMessages, copiedId, onDownloadPDF, onCopyToClipboard }: SalesKitResultProps) {
  return (
    <div className="space-y-8 rounded-3xl border border-slate-200 bg-white p-8 shadow-sm ring-1 ring-slate-200">
      <div>
        <h2 className="text-2xl font-semibold text-slate-900">Готовый Sales Kit</h2>
        <p className="mt-2 text-sm text-slate-600">Все материалы готовы для использования. Скопируйте тексты, скачайте PDF или используйте напрямую.</p>
      </div>

      {composition.pdf && <div className="space-y-4"><div className="flex items-center justify-between"><h3 className="text-xl font-semibold text-slate-900">PDF-презентация на 6 слайдов</h3><button onClick={onDownloadPDF} className="inline-flex items-center justify-center rounded-xl bg-slate-900 px-5 py-2 text-sm font-semibold text-white transition hover:bg-slate-700">Скачать PDF</button></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[{ num: 1, title: "Обложка", desc: "Название проекта, девелопер, изображение объекта" }, { num: 2, title: "Общее описание", desc: "О проекте, локация, тип апартаментов, архитектура" }, { num: 3, title: "Ключевая информация", desc: "Цены, площади, спальни, сроки сдачи, условия покупки" }, { num: 4, title: "Локация и инфраструктура", desc: "Карта, близость к транспорту, магазины, рестораны, парки" }, { num: 5, title: "Инвестиционная привлекательность", desc: "ROI-сценарии, рост стоимости, арендная доходность, преимущества" }, { num: 6, title: "Условия покупки + CTA", desc: "Гибкий график платежей, визовая поддержка, контакты" }].map((slide) => <div key={slide.num} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="mb-2 inline-flex rounded-full bg-slate-900 px-3 py-1 text-sm font-semibold text-white">Слайд {slide.num}</div><h4 className="mt-2 font-semibold text-slate-900">{slide.title}</h4><p className="mt-1 text-sm text-slate-600">{slide.desc}</p></div>)}</div></div>}
      {composition.telegram && <div className="space-y-4"><div className="flex items-center justify-between"><h3 className="text-xl font-semibold text-slate-900">Telegram-пост</h3><button onClick={() => onCopyToClipboard(telegramPostText, "telegram")} className={`inline-flex items-center justify-center rounded-xl px-5 py-2 text-sm font-semibold transition ${copiedId === "telegram" ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-900 hover:bg-slate-300"}`}>{copiedId === "telegram" ? "✓ Скопировано" : "Скопировать"}</button></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-7 text-slate-700">{telegramPostText.split("\n").map((line, idx) => <div key={idx}>{line}</div>)}</div></div>}
      {composition.roi && <div className="space-y-4"><h3 className="text-xl font-semibold text-slate-900">ROI-блок</h3><div className="grid gap-4 md:grid-cols-3">{roiData.map((roi) => <div key={roi.scenario} className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><h4 className="font-semibold text-slate-900">{roi.scenario}</h4><p className="mt-1 text-xs text-slate-600">{roi.description}</p><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span className="text-slate-600">Начальные инвестиции:</span><span className="font-semibold text-slate-900">{roi.initialInvestment} THB</span></div><div className="flex justify-between border-t border-slate-200 pt-2"><span className="text-slate-600">ROI за 1 год:</span><span className="font-semibold text-emerald-700">+{roi.roi1Year} THB</span></div><div className="flex justify-between"><span className="text-slate-600">ROI за 3 года:</span><span className="font-semibold text-emerald-700">+{roi.roi3Year} THB</span></div><div className="flex justify-between"><span className="text-slate-600">ROI за 5 лет:</span><span className="font-semibold text-emerald-700">+{roi.roi5Year} THB</span></div></div></div>)}</div></div>}
      {composition.faq && <div className="space-y-4"><div className="flex items-center justify-between"><h3 className="text-xl font-semibold text-slate-900">FAQ на 7 вопросов</h3><button onClick={() => onCopyToClipboard(faqData.map((f) => `${f.question}\n${f.answer}`).join("\n\n"), "faq")} className={`inline-flex items-center justify-center rounded-xl px-5 py-2 text-sm font-semibold transition ${copiedId === "faq" ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-900 hover:bg-slate-300"}`}>{copiedId === "faq" ? "✓ Скопировано" : "Скопировать FAQ"}</button></div><div className="space-y-3">{faqData.map((faq, idx) => <details key={idx} className="group rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="flex cursor-pointer items-center justify-between font-medium text-slate-900"><span>{faq.question}</span><span className="text-slate-400 group-open:rotate-180 transition">▼</span></summary><p className="mt-3 text-sm text-slate-600">{faq.answer}</p></details>)}</div></div>}
      {composition.followup && <div className="space-y-4"><div className="flex items-center justify-between"><h3 className="text-xl font-semibold text-slate-900">3 Follow-up сообщения</h3><button onClick={() => onCopyToClipboard(followupMessages.map((m) => `[${m.day}]\n${m.subject}\n${m.text}`).join("\n\n---\n\n"), "followup")} className={`inline-flex items-center justify-center rounded-xl px-5 py-2 text-sm font-semibold transition ${copiedId === "followup" ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-900 hover:bg-slate-300"}`}>{copiedId === "followup" ? "✓ Скопировано" : "Скопировать follow-up"}</button></div><div className="space-y-3">{followupMessages.map((msg, idx) => <div key={idx} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="mb-2 flex items-center gap-2"><span className="inline-flex rounded-full bg-slate-900 px-3 py-1 text-xs font-semibold text-white">{msg.day}</span><span className="font-semibold text-slate-900">{msg.subject}</span></div><p className="text-sm text-slate-600">{msg.text}</p></div>)}</div></div>}

      <div className="rounded-2xl border border-slate-200 bg-yellow-50 p-4"><p className="text-xs leading-6 text-slate-600"><span className="font-semibold text-slate-900">Дисклеймер:</span> Цены, наличие и условия покупки требуют подтверждения у застройщика или официального представителя. ROI является прогнозной оценкой и не является финансовой рекомендацией или гарантией доходности.</p></div>
      <div className="flex flex-col gap-3 sm:flex-row"><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white px-6 py-3 text-sm font-semibold text-slate-900 transition hover:bg-slate-50">Создать ещё один Sales Kit</button><button onClick={() => (window.location.href = "/")} className="inline-flex items-center justify-center rounded-xl bg-slate-900 px-6 py-3 text-sm font-semibold text-white transition hover:bg-slate-700">Вернуться на главную</button></div>
    </div>
  );
}
